/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model.tables;


import br.lehmkuhl.jooq.model.Keys;
import br.lehmkuhl.jooq.model.Servicofloripa;
import br.lehmkuhl.jooq.model.tables.records.BudgetRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Budget extends TableImpl<BudgetRecord> {

    private static final long serialVersionUID = -1536329294;

    /**
     * The reference instance of <code>servicofloripa.budget</code>
     */
    public static final Budget BUDGET = new Budget();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BudgetRecord> getRecordType() {
        return BudgetRecord.class;
    }

    /**
     * The column <code>servicofloripa.budget.id</code>.
     */
    public final TableField<BudgetRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>servicofloripa.budget.email</code>.
     */
    public final TableField<BudgetRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>servicofloripa.budget.name</code>.
     */
    public final TableField<BudgetRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>servicofloripa.budget.phone</code>.
     */
    public final TableField<BudgetRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(15).nullable(false), this, "");

    /**
     * The column <code>servicofloripa.budget.viewed_admin</code>.
     */
    public final TableField<BudgetRecord, Byte> VIEWED_ADMIN = createField("viewed_admin", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>servicofloripa.budget.created_date</code>.
     */
    public final TableField<BudgetRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>servicofloripa.budget</code> table reference
     */
    public Budget() {
        this("budget", null);
    }

    /**
     * Create an aliased <code>servicofloripa.budget</code> table reference
     */
    public Budget(String alias) {
        this(alias, BUDGET);
    }

    private Budget(String alias, Table<BudgetRecord> aliased) {
        this(alias, aliased, null);
    }

    private Budget(String alias, Table<BudgetRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Servicofloripa.SERVICOFLORIPA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<BudgetRecord, Long> getIdentity() {
        return Keys.IDENTITY_BUDGET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BudgetRecord> getPrimaryKey() {
        return Keys.KEY_BUDGET_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BudgetRecord>> getKeys() {
        return Arrays.<UniqueKey<BudgetRecord>>asList(Keys.KEY_BUDGET_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Budget as(String alias) {
        return new Budget(alias, this);
    }

    /**
     * Rename this table
     */
    public Budget rename(String name) {
        return new Budget(name, null);
    }
}
