/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model.tables;


import br.lehmkuhl.jooq.model.Keys;
import br.lehmkuhl.jooq.model.Servicofloripa;
import br.lehmkuhl.jooq.model.tables.records.ProfessionalRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Professional extends TableImpl<ProfessionalRecord> {

    private static final long serialVersionUID = -1944926649;

    /**
     * The reference instance of <code>servicofloripa.professional</code>
     */
    public static final Professional PROFESSIONAL = new Professional();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessionalRecord> getRecordType() {
        return ProfessionalRecord.class;
    }

    /**
     * The column <code>servicofloripa.professional.id</code>.
     */
    public final TableField<ProfessionalRecord, Long> ID = createField("id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>servicofloripa.professional.email</code>.
     */
    public final TableField<ProfessionalRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(45).nullable(false), this, "");

    /**
     * The column <code>servicofloripa.professional.name</code>.
     */
    public final TableField<ProfessionalRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

    /**
     * The column <code>servicofloripa.professional.url_image</code>.
     */
    public final TableField<ProfessionalRecord, String> URL_IMAGE = createField("url_image", org.jooq.impl.SQLDataType.VARCHAR.length(500), this, "");

    /**
     * The column <code>servicofloripa.professional.created_date</code>.
     */
    public final TableField<ProfessionalRecord, Timestamp> CREATED_DATE = createField("created_date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>servicofloripa.professional.order</code>.
     */
    public final TableField<ProfessionalRecord, Integer> ORDER = createField("order", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>servicofloripa.professional</code> table reference
     */
    public Professional() {
        this("professional", null);
    }

    /**
     * Create an aliased <code>servicofloripa.professional</code> table reference
     */
    public Professional(String alias) {
        this(alias, PROFESSIONAL);
    }

    private Professional(String alias, Table<ProfessionalRecord> aliased) {
        this(alias, aliased, null);
    }

    private Professional(String alias, Table<ProfessionalRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Servicofloripa.SERVICOFLORIPA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProfessionalRecord, Long> getIdentity() {
        return Keys.IDENTITY_PROFESSIONAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProfessionalRecord> getPrimaryKey() {
        return Keys.KEY_PROFESSIONAL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProfessionalRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessionalRecord>>asList(Keys.KEY_PROFESSIONAL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Professional as(String alias) {
        return new Professional(alias, this);
    }

    /**
     * Rename this table
     */
    public Professional rename(String name) {
        return new Professional(name, null);
    }
}
