/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model.tables;


import br.lehmkuhl.jooq.model.Keys;
import br.lehmkuhl.jooq.model.Servicofloripa;
import br.lehmkuhl.jooq.model.tables.records.ProfessionalServiceRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessionalService extends TableImpl<ProfessionalServiceRecord> {

    private static final long serialVersionUID = -541895759;

    /**
     * The reference instance of <code>servicofloripa.professional_service</code>
     */
    public static final ProfessionalService PROFESSIONAL_SERVICE = new ProfessionalService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfessionalServiceRecord> getRecordType() {
        return ProfessionalServiceRecord.class;
    }

    /**
     * The column <code>servicofloripa.professional_service.professional_id</code>.
     */
    public final TableField<ProfessionalServiceRecord, Long> PROFESSIONAL_ID = createField("professional_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>servicofloripa.professional_service.service_id</code>.
     */
    public final TableField<ProfessionalServiceRecord, Long> SERVICE_ID = createField("service_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * Create a <code>servicofloripa.professional_service</code> table reference
     */
    public ProfessionalService() {
        this("professional_service", null);
    }

    /**
     * Create an aliased <code>servicofloripa.professional_service</code> table reference
     */
    public ProfessionalService(String alias) {
        this(alias, PROFESSIONAL_SERVICE);
    }

    private ProfessionalService(String alias, Table<ProfessionalServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private ProfessionalService(String alias, Table<ProfessionalServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Servicofloripa.SERVICOFLORIPA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProfessionalServiceRecord> getPrimaryKey() {
        return Keys.KEY_PROFESSIONAL_SERVICE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProfessionalServiceRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfessionalServiceRecord>>asList(Keys.KEY_PROFESSIONAL_SERVICE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProfessionalServiceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProfessionalServiceRecord, ?>>asList(Keys.FK_PROFESSIONAL_SERVICE_PROFESSIONAL, Keys.FK_PROFESSIONAL_SERVICE_SERVICE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfessionalService as(String alias) {
        return new ProfessionalService(alias, this);
    }

    /**
     * Rename this table
     */
    public ProfessionalService rename(String name) {
        return new ProfessionalService(name, null);
    }
}
