-- MySQL Script generated by MySQL Workbench
-- 01/14/17 22:00:51
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema servicofloripa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema servicofloripa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `servicofloripa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `servicofloripa` ;

-- -----------------------------------------------------
-- Table `servicofloripa`.`professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`professional` (
  `id` BIGINT(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `url_image` VARCHAR(500) NULL,
  `created_date` DATETIME NOT NULL,
  `order` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`budget`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`budget` (
  `id` BIGINT(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `viewed_admin` TINYINT(1) NOT NULL DEFAULT 0,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`service` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `created_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`professional_service`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`professional_service` (
  `professional_id` BIGINT(20) NOT NULL,
  `service_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`professional_id`, `service_id`),
  INDEX `fk_professional_has_service_service1_idx` (`service_id` ASC),
  INDEX `fk_professional_has_service_professional_idx` (`professional_id` ASC),
  CONSTRAINT `fk_professional_service_professional`
    FOREIGN KEY (`professional_id`)
    REFERENCES `servicofloripa`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_service_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `servicofloripa`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`budget_professional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`budget_professional` (
  `budget_id` BIGINT(20) NOT NULL,
  `professional_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`budget_id`, `professional_id`),
  INDEX `fk_budget_professional_professional` (`professional_id` ASC),
  INDEX `fk_budget_professional_budget` (`budget_id` ASC),
  CONSTRAINT `fk_budget_has_professional_budget1`
    FOREIGN KEY (`budget_id`)
    REFERENCES `servicofloripa`.`budget` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_budget_has_professional_professional1`
    FOREIGN KEY (`professional_id`)
    REFERENCES `servicofloripa`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`contact` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(15) NOT NULL,
  `whatsapp` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `servicofloripa`.`professional_contact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `servicofloripa`.`professional_contact` (
  `professional_id` BIGINT(20) NOT NULL,
  `contact_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`professional_id`, `contact_id`),
  INDEX `fk_professional_has_contact_contact1_idx` (`contact_id` ASC),
  INDEX `fk_professional_has_contact_professional1_idx` (`professional_id` ASC),
  CONSTRAINT `fk_professional_contact_professional`
    FOREIGN KEY (`professional_id`)
    REFERENCES `servicofloripa`.`professional` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_professional_contact_contact`
    FOREIGN KEY (`contact_id`)
    REFERENCES `servicofloripa`.`contact` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



ALTER TABLE `servicofloripa`.`professional` 
ADD COLUMN `order` INT NOT NULL AFTER `created_date`;
