/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model;


import br.lehmkuhl.jooq.model.tables.Budget;
import br.lehmkuhl.jooq.model.tables.BudgetProfessional;
import br.lehmkuhl.jooq.model.tables.Contact;
import br.lehmkuhl.jooq.model.tables.Professional;
import br.lehmkuhl.jooq.model.tables.ProfessionalContact;
import br.lehmkuhl.jooq.model.tables.ProfessionalService;
import br.lehmkuhl.jooq.model.tables.Service;
import br.lehmkuhl.jooq.model.tables.records.BudgetProfessionalRecord;
import br.lehmkuhl.jooq.model.tables.records.BudgetRecord;
import br.lehmkuhl.jooq.model.tables.records.ContactRecord;
import br.lehmkuhl.jooq.model.tables.records.ProfessionalContactRecord;
import br.lehmkuhl.jooq.model.tables.records.ProfessionalRecord;
import br.lehmkuhl.jooq.model.tables.records.ProfessionalServiceRecord;
import br.lehmkuhl.jooq.model.tables.records.ServiceRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>servicofloripa</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<BudgetRecord, Long> IDENTITY_BUDGET = Identities0.IDENTITY_BUDGET;
    public static final Identity<ContactRecord, Long> IDENTITY_CONTACT = Identities0.IDENTITY_CONTACT;
    public static final Identity<ProfessionalRecord, Long> IDENTITY_PROFESSIONAL = Identities0.IDENTITY_PROFESSIONAL;
    public static final Identity<ServiceRecord, Long> IDENTITY_SERVICE = Identities0.IDENTITY_SERVICE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BudgetRecord> KEY_BUDGET_PRIMARY = UniqueKeys0.KEY_BUDGET_PRIMARY;
    public static final UniqueKey<BudgetProfessionalRecord> KEY_BUDGET_PROFESSIONAL_PRIMARY = UniqueKeys0.KEY_BUDGET_PROFESSIONAL_PRIMARY;
    public static final UniqueKey<ContactRecord> KEY_CONTACT_PRIMARY = UniqueKeys0.KEY_CONTACT_PRIMARY;
    public static final UniqueKey<ProfessionalRecord> KEY_PROFESSIONAL_PRIMARY = UniqueKeys0.KEY_PROFESSIONAL_PRIMARY;
    public static final UniqueKey<ProfessionalContactRecord> KEY_PROFESSIONAL_CONTACT_PRIMARY = UniqueKeys0.KEY_PROFESSIONAL_CONTACT_PRIMARY;
    public static final UniqueKey<ProfessionalServiceRecord> KEY_PROFESSIONAL_SERVICE_PRIMARY = UniqueKeys0.KEY_PROFESSIONAL_SERVICE_PRIMARY;
    public static final UniqueKey<ServiceRecord> KEY_SERVICE_PRIMARY = UniqueKeys0.KEY_SERVICE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BudgetProfessionalRecord, BudgetRecord> FK_BUDGET_HAS_PROFESSIONAL_BUDGET1 = ForeignKeys0.FK_BUDGET_HAS_PROFESSIONAL_BUDGET1;
    public static final ForeignKey<BudgetProfessionalRecord, ProfessionalRecord> FK_BUDGET_HAS_PROFESSIONAL_PROFESSIONAL1 = ForeignKeys0.FK_BUDGET_HAS_PROFESSIONAL_PROFESSIONAL1;
    public static final ForeignKey<ProfessionalContactRecord, ProfessionalRecord> FK_PROFESSIONAL_CONTACT_PROFESSIONAL = ForeignKeys0.FK_PROFESSIONAL_CONTACT_PROFESSIONAL;
    public static final ForeignKey<ProfessionalContactRecord, ContactRecord> FK_PROFESSIONAL_CONTACT_CONTACT = ForeignKeys0.FK_PROFESSIONAL_CONTACT_CONTACT;
    public static final ForeignKey<ProfessionalServiceRecord, ProfessionalRecord> FK_PROFESSIONAL_SERVICE_PROFESSIONAL = ForeignKeys0.FK_PROFESSIONAL_SERVICE_PROFESSIONAL;
    public static final ForeignKey<ProfessionalServiceRecord, ServiceRecord> FK_PROFESSIONAL_SERVICE_SERVICE = ForeignKeys0.FK_PROFESSIONAL_SERVICE_SERVICE;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<BudgetRecord, Long> IDENTITY_BUDGET = createIdentity(Budget.BUDGET, Budget.BUDGET.ID);
        public static Identity<ContactRecord, Long> IDENTITY_CONTACT = createIdentity(Contact.CONTACT, Contact.CONTACT.ID);
        public static Identity<ProfessionalRecord, Long> IDENTITY_PROFESSIONAL = createIdentity(Professional.PROFESSIONAL, Professional.PROFESSIONAL.ID);
        public static Identity<ServiceRecord, Long> IDENTITY_SERVICE = createIdentity(Service.SERVICE, Service.SERVICE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<BudgetRecord> KEY_BUDGET_PRIMARY = createUniqueKey(Budget.BUDGET, "KEY_budget_PRIMARY", Budget.BUDGET.ID);
        public static final UniqueKey<BudgetProfessionalRecord> KEY_BUDGET_PROFESSIONAL_PRIMARY = createUniqueKey(BudgetProfessional.BUDGET_PROFESSIONAL, "KEY_budget_professional_PRIMARY", BudgetProfessional.BUDGET_PROFESSIONAL.BUDGET_ID, BudgetProfessional.BUDGET_PROFESSIONAL.PROFESSIONAL_ID);
        public static final UniqueKey<ContactRecord> KEY_CONTACT_PRIMARY = createUniqueKey(Contact.CONTACT, "KEY_contact_PRIMARY", Contact.CONTACT.ID);
        public static final UniqueKey<ProfessionalRecord> KEY_PROFESSIONAL_PRIMARY = createUniqueKey(Professional.PROFESSIONAL, "KEY_professional_PRIMARY", Professional.PROFESSIONAL.ID);
        public static final UniqueKey<ProfessionalContactRecord> KEY_PROFESSIONAL_CONTACT_PRIMARY = createUniqueKey(ProfessionalContact.PROFESSIONAL_CONTACT, "KEY_professional_contact_PRIMARY", ProfessionalContact.PROFESSIONAL_CONTACT.PROFESSIONAL_ID, ProfessionalContact.PROFESSIONAL_CONTACT.CONTACT_ID);
        public static final UniqueKey<ProfessionalServiceRecord> KEY_PROFESSIONAL_SERVICE_PRIMARY = createUniqueKey(ProfessionalService.PROFESSIONAL_SERVICE, "KEY_professional_service_PRIMARY", ProfessionalService.PROFESSIONAL_SERVICE.PROFESSIONAL_ID, ProfessionalService.PROFESSIONAL_SERVICE.SERVICE_ID);
        public static final UniqueKey<ServiceRecord> KEY_SERVICE_PRIMARY = createUniqueKey(Service.SERVICE, "KEY_service_PRIMARY", Service.SERVICE.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<BudgetProfessionalRecord, BudgetRecord> FK_BUDGET_HAS_PROFESSIONAL_BUDGET1 = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_BUDGET_PRIMARY, BudgetProfessional.BUDGET_PROFESSIONAL, "fk_budget_has_professional_budget1", BudgetProfessional.BUDGET_PROFESSIONAL.BUDGET_ID);
        public static final ForeignKey<BudgetProfessionalRecord, ProfessionalRecord> FK_BUDGET_HAS_PROFESSIONAL_PROFESSIONAL1 = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_PROFESSIONAL_PRIMARY, BudgetProfessional.BUDGET_PROFESSIONAL, "fk_budget_has_professional_professional1", BudgetProfessional.BUDGET_PROFESSIONAL.PROFESSIONAL_ID);
        public static final ForeignKey<ProfessionalContactRecord, ProfessionalRecord> FK_PROFESSIONAL_CONTACT_PROFESSIONAL = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_PROFESSIONAL_PRIMARY, ProfessionalContact.PROFESSIONAL_CONTACT, "fk_professional_contact_professional", ProfessionalContact.PROFESSIONAL_CONTACT.PROFESSIONAL_ID);
        public static final ForeignKey<ProfessionalContactRecord, ContactRecord> FK_PROFESSIONAL_CONTACT_CONTACT = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_CONTACT_PRIMARY, ProfessionalContact.PROFESSIONAL_CONTACT, "fk_professional_contact_contact", ProfessionalContact.PROFESSIONAL_CONTACT.CONTACT_ID);
        public static final ForeignKey<ProfessionalServiceRecord, ProfessionalRecord> FK_PROFESSIONAL_SERVICE_PROFESSIONAL = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_PROFESSIONAL_PRIMARY, ProfessionalService.PROFESSIONAL_SERVICE, "fk_professional_service_professional", ProfessionalService.PROFESSIONAL_SERVICE.PROFESSIONAL_ID);
        public static final ForeignKey<ProfessionalServiceRecord, ServiceRecord> FK_PROFESSIONAL_SERVICE_SERVICE = createForeignKey(br.lehmkuhl.jooq.model.Keys.KEY_SERVICE_PRIMARY, ProfessionalService.PROFESSIONAL_SERVICE, "fk_professional_service_service", ProfessionalService.PROFESSIONAL_SERVICE.SERVICE_ID);
    }
}
