/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model;


import br.lehmkuhl.jooq.model.tables.Budget;
import br.lehmkuhl.jooq.model.tables.BudgetProfessional;
import br.lehmkuhl.jooq.model.tables.Contact;
import br.lehmkuhl.jooq.model.tables.Professional;
import br.lehmkuhl.jooq.model.tables.ProfessionalContact;
import br.lehmkuhl.jooq.model.tables.ProfessionalService;
import br.lehmkuhl.jooq.model.tables.Service;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in servicofloripa
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>servicofloripa.budget</code>.
     */
    public static final Budget BUDGET = br.lehmkuhl.jooq.model.tables.Budget.BUDGET;

    /**
     * The table <code>servicofloripa.budget_professional</code>.
     */
    public static final BudgetProfessional BUDGET_PROFESSIONAL = br.lehmkuhl.jooq.model.tables.BudgetProfessional.BUDGET_PROFESSIONAL;

    /**
     * The table <code>servicofloripa.contact</code>.
     */
    public static final Contact CONTACT = br.lehmkuhl.jooq.model.tables.Contact.CONTACT;

    /**
     * The table <code>servicofloripa.professional</code>.
     */
    public static final Professional PROFESSIONAL = br.lehmkuhl.jooq.model.tables.Professional.PROFESSIONAL;

    /**
     * The table <code>servicofloripa.professional_contact</code>.
     */
    public static final ProfessionalContact PROFESSIONAL_CONTACT = br.lehmkuhl.jooq.model.tables.ProfessionalContact.PROFESSIONAL_CONTACT;

    /**
     * The table <code>servicofloripa.professional_service</code>.
     */
    public static final ProfessionalService PROFESSIONAL_SERVICE = br.lehmkuhl.jooq.model.tables.ProfessionalService.PROFESSIONAL_SERVICE;

    /**
     * The table <code>servicofloripa.service</code>.
     */
    public static final Service SERVICE = br.lehmkuhl.jooq.model.tables.Service.SERVICE;
}
