/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model.tables.records;


import br.lehmkuhl.jooq.model.tables.BudgetProfessional;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BudgetProfessionalRecord extends UpdatableRecordImpl<BudgetProfessionalRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1463483882;

    /**
     * Setter for <code>servicofloripa.budget_professional.budget_id</code>.
     */
    public void setBudgetId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>servicofloripa.budget_professional.budget_id</code>.
     */
    public Long getBudgetId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>servicofloripa.budget_professional.professional_id</code>.
     */
    public void setProfessionalId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>servicofloripa.budget_professional.professional_id</code>.
     */
    public Long getProfessionalId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return BudgetProfessional.BUDGET_PROFESSIONAL.BUDGET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return BudgetProfessional.BUDGET_PROFESSIONAL.PROFESSIONAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getBudgetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getProfessionalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BudgetProfessionalRecord value1(Long value) {
        setBudgetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BudgetProfessionalRecord value2(Long value) {
        setProfessionalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BudgetProfessionalRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BudgetProfessionalRecord
     */
    public BudgetProfessionalRecord() {
        super(BudgetProfessional.BUDGET_PROFESSIONAL);
    }

    /**
     * Create a detached, initialised BudgetProfessionalRecord
     */
    public BudgetProfessionalRecord(Long budgetId, Long professionalId) {
        super(BudgetProfessional.BUDGET_PROFESSIONAL);

        set(0, budgetId);
        set(1, professionalId);
    }
}
