/**
 * This class is generated by jOOQ
 */
package br.lehmkuhl.jooq.model.tables.records;


import br.lehmkuhl.jooq.model.tables.ProfessionalService;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProfessionalServiceRecord extends UpdatableRecordImpl<ProfessionalServiceRecord> implements Record2<Long, Long> {

    private static final long serialVersionUID = -1107156120;

    /**
     * Setter for <code>servicofloripa.professional_service.professional_id</code>.
     */
    public void setProfessionalId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>servicofloripa.professional_service.professional_id</code>.
     */
    public Long getProfessionalId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>servicofloripa.professional_service.service_id</code>.
     */
    public void setServiceId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>servicofloripa.professional_service.service_id</code>.
     */
    public Long getServiceId() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Long, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return ProfessionalService.PROFESSIONAL_SERVICE.PROFESSIONAL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return ProfessionalService.PROFESSIONAL_SERVICE.SERVICE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getProfessionalId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getServiceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfessionalServiceRecord value1(Long value) {
        setProfessionalId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfessionalServiceRecord value2(Long value) {
        setServiceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProfessionalServiceRecord values(Long value1, Long value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProfessionalServiceRecord
     */
    public ProfessionalServiceRecord() {
        super(ProfessionalService.PROFESSIONAL_SERVICE);
    }

    /**
     * Create a detached, initialised ProfessionalServiceRecord
     */
    public ProfessionalServiceRecord(Long professionalId, Long serviceId) {
        super(ProfessionalService.PROFESSIONAL_SERVICE);

        set(0, professionalId);
        set(1, serviceId);
    }
}
